#!/bin/bash

# Check if a grammar file was provided
if [ -z "$1" ]; then
    echo "Usage: $0 <GrammarFile.g4> [input_file.txt]"
    exit 1
fi

GRAMMAR_FILE="$1"
INPUT_FILE="$2"
ASM_FILE="$(pwd)/output/code.asm"   # <-- change this if your compiler outputs a different filename
OUT_FILE="$(pwd)/code.out"

# 1. Generate parser C++ files from the target grammar
antlr4 -v 4.13.2 -Dlanguage=Cpp -visitor -no-listener "$GRAMMAR_FILE"

# 2. Compile all .cpp files
g++ -std=c++17 -w -I/usr/local/include/antlr4-runtime *.cpp -L/usr/local/lib64/ -lantlr4-runtime -pthread -o compiler.out

if [ ! -f ./compiler.out ]; then
    echo "Error: compiler.out was not built."
    exit 1
fi

# 3. Run the compiled executable with optional input file, producing $ASM_FILE
if [ -n "$INPUT_FILE" ]; then
    LD_LIBRARY_PATH=/usr/local/lib64 ./compiler.out "$INPUT_FILE"
else
    LD_LIBRARY_PATH=/usr/local/lib64 ./compiler.out
fi

if [ ! -f "$ASM_FILE" ]; then
    echo "Error: $ASM_FILE was not generated by compiler.out."
    exit 1
fi

# 4. Assemble the generated FASM code into an ELF executable
# Note: fasm is an x86 binary, run here on an ARM host via FEX emulation.
# muvm runs the emulator inside a microVM, which does NOT preserve the host's
# working directory, so absolute paths are required (relative paths silently
# fail with "source file not found").
muvm -- fasm "$ASM_FILE" "$OUT_FILE"

if [ ! -f "$OUT_FILE" ]; then
    echo "Error: fasm failed to produce $OUT_FILE."
    exit 1
fi

chmod +x "$OUT_FILE"

# 5. Run the resulting binary
echo "----- Running compiled program -----"
"$OUT_FILE"
echo "----- Exit code: $? -----"